name: 3d-photo-impainting
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.13
  - pytorch==1.4.0
  - torchvision==0.5.0
  - cudatoolkit==10.1.243
  - pip==22.1.2
  - pyyaml==3.13
  - pip:
    - scipy==1.7.3
    - torch===1.4.0
    - torchvision===0.5.0
    - opencv-python==4.2.0.32
    - vispy==0.6.4
    - moviepy==1.0.2
    - transforms3d==0.3.1
    - networkx==2.3
    - numpy==1.21.6
    - scikit-image==0.18.3
    - Pillow==7.1.2