name: styletransfer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy
  - pillow
  - matplotlib
  - protobuf
  - tqdm

  - pip:
    - torch
    - torchvision
    - opencv-python
    - piexif
    - azure-storage-queue
    - azure-storage-blob
    - applicationinsights
