name: base
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - pip
  - pytorch
  - scipy
  - pyyaml
  - matplotlib
  - scikit-image
  - pip:
    - torchvision
    - opencv-python
    - vispy
    - moviepy
    - transforms3d
    - networkx
    - piexif
    - azure-storage-queue
    - azure-storage-blob
    - applicationinsights
